version: '3.3'
services:

  frontend:
    image: chusj/clin-frontend:1.5.0
    environment:
      DOMAIN: "dev.chusj-clin-dev.org"
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.app_role == generic]
      resources:
        limits:
          cpus: '2.00'
          memory: 1024M
        reservations:
          cpus: '1.00'
          memory: 512M
    networks:
      - proxy

networks:
  proxy:
    external: true
